version: '3.7'

services:
  ssapi:
    image: dsezerpy/ssapi:latest
    restart: unless-stopped
    depends_on:
      - database
    ports:
      # Replace 7136 with whichever port you want to connect from
      - "127.0.0.1:7136:80"
    environment:
      # (Required) MongoDB Database Connection String
      - SSAPI_MONGODB_CONNSTR=mongodb://ssapi:ssapi@database:27017/ssapi
      # (Optional) MongoDB Database
      - SSAPI_MONGODB_DATABASE=ssapi
      # (Required) JWT Settings
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  database:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ssapi
      MONGO_INITDB_ROOT_PASSWORD: ssapi
      CREATE_DATABASE: true
    # Recommended: Put the MongoDB files somewhere in your local drive
    # so you can copy them to somewhere else if you ever need to
    volumes:
      - ./mongo:/data/db
    command: sh -c 'if [ "$CREATE_DATABASE" = "true" ]; then mongod --bind_ip_all; fi'
